security:

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_MANAGER, ROLE_REPO]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        App\Entity\User: 'auto'

    providers:
        users:
            entity:
                class: App\Entity\User
        clients:
            entity:
                class: App\Entity\Client
                property: token
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#
#        api:
#            pattern: ^/api
#            stateless: true
#            simple_preauth:
#                authenticator: devliver.security.token_authenticator
#            provider: api_token_provider
#
        repo:
            pattern: ^/repo/(.*)
            context: repo
            anonymous: true
            stateless: true
            lazy: true
            logout: ~
            provider: clients
            guard:
                authenticators:
                    - App\Security\Guard\Authenticator\RepositoryAuthenticator

        main:
            user_checker: App\Security\Checker\UserChecker
            pattern: ^/
            context: user
            anonymous: true
            provider: users
            guard:
                authenticators:
                    - App\Security\Guard\Authenticator\LoginFormAuthenticator
            logout:
                path: /logout
                target: /
                invalidate_session: true

    access_control:
        - { path: ^/packages.json, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/track-downloads, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/setup, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/repo/, role: ROLE_REPO }

        - { path: ^/.*, role: ROLE_USER }