parameters:
    locale: "%env(LOCALE)%"
        
    devliver_dir:           '%kernel.project_dir%/data'
    devliver_dist_dir:      '%devliver_dir%/dist'
    devliver_composer_dir:  '%devliver_dir%/composer'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $composerDirectory: '%devliver_composer_dir%'
            $distDir: '%devliver_dist_dir%'
            $apiKey: '%env(APP_API_KEY)%'
            Symfony\Component\Cache\Adapter\TagAwareAdapterInterface: '@cache.tag.app'

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags: ['doctrine.event_subscriber']

    App\:
        resource: '../src/*'
        exclude: '../src/{Controller,Domain,DependencyInjection,Entity,Model,Infrastructure,Tests,Kernel.php,bootstrap.php}'
        
    cache.tag.app:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        decorates: cache.app
        arguments: ['@cache.tag.app.inner']

#    # controller
    App\Controller\:
        resource: '../src/Controller/*'
        tags: ['controller.service_arguments']
